# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      # Docker container with Python installed
      # https://circleci.com/docs/2.0/circleci-images/#python
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      # -------------------------------------------------------------------------------
      - run:
          name: install
          command: |
            # Install testing and linting requirements
            pip install pytest
            pip install black
            
      # -------------------------------------------------------------------------------
      - run:
          name: test-optimizing-meals
          command: |
            cd optimizing_meals
            pip install -r requirements.txt
            pytest optimizing_meals.py classes.py --doctest-modules --capture=sys
            black optimizing_meals.py --check -l 79
            cd ..